name: ma_FNPVP
main: com.github.caaarlowsz.fantasymc.kitpvp.FantasyKits
author: zAlpha_
version: 2.5
commands:
   construir:
   kit:
   spawn:
   setwarp:
   tag:
   toggle:
   inv:
   tell:
   fly:
   gm:
   gamemode:
   tp:
   sc:
   staffchat:
   dinheiro:
   chaves:
   caixas:
   report:
   1v1:
   admin:
   youtuber:
   bc:
   chat:
   status:
   tpall:
   skit:
   limpar:
   score:
